export const Chaldean = [
  {
    LifeNumber: 1,
    title: 'The Trailblazer',
    destiny: 'You have a winner mentality, one which desires freedom and abundance.You want to achieve success in whatever you do, you want a life you desire.You are very bent on "making it happen".You also dislike authority, because you want to be an authoritative figure yourself! You like to delegate work and make sure other people do their job.You dislike people who are sloppy, people without the drive to do better, people without ambition or goals.You are very creative and somewhat of a "Perfectionist".You have a hard time dealing with problems, because you do not want any blockages in your path to success, you want everything to flow easily.You want to live your life with maximized pleasures and minimizing any sort of pain or discomfort, you crave for abundance and freedom. You are very self-reliant and you embody the qualities of the sun, you burn bright, you want to shine, nourish those who are under your guidance and lead a successful and vital life. You have an unyielding zest for life, you radiate with positivity, and you want to grow in life. You always aim for more and try to do better. You often find yourself thinking about a life where you are reliant on your creative power, much like a river, you demand flow of freedom, movement and expression. You possess a strong belief in your capabilities and even though you do not like to admit it but you like to seek affirmation and recognition from others, in short words you like it when people praise you! But it is okay! Because you deserve it for your efforts and talents. However, you may be a little stubborn sometimes, even though you might not admit it, but you always like to be right or the one who makes no mistake. You may believe that making a mistake might make your peers question your talents and credibility, but it only makes you human. You may also have a thing for luxury, you like tasteful things, like rings, watches, chains etc., anything that may demonstrate your opulence. Emotional challenges for you include tendencies towards vanity, you may come off as arrogant and be labeled as a narcissist. You may have trouble accepting advice, feedback or constructive criticism. You always want to win and you see "losing" as a step back. Which is not true, sometimes things do not go as planned and that is okay. But that does not mean you lost.'
  },
  {
    LifeNumber: 2,
    title: 'The Harmonizer',
    destiny: 'You are soft, like water, you are emotional. People may see that as your weakness, but that is your strength. You can feel things deeply, you can connect to others deeply. You are a born Empath, you tend to get melancholic easily. Your ability to feel deeply helps you be creative, your creativity is mostly influenced by your emotions. Your main strength is the ability to read people and understand them. You are able to feel some one else\'s pain, which makes you a trusted friend and a diary for a lot of people around you. People naturally feel comfortable sharing their secrets or past with you. Which is why you often find yourself entrusted with information about a person, that nobody else knows about. However sometimes you may get swept up into your emotions and may fail to see the bigger picture, which you later realize and regret. You are somewhat of a Overthinker.You are characterized by your sensitive , open and profound nature. You are gentle, charming and a bad liar. You may find that the moon has an effect on your emotions, the moon plays with your emotions, sometimes you are happy when the moon is full and maybe melancholic when you do not see it in the sky. Sometimes you may catch yourself pondering on if you belonged to this world or this age. You value shrink and tranquility , and shy away from loud noises or crowded places. You are a helping hand in need.You are affected by arguments or heated debates, and their side effects may appear in the form of headaches, exhaustion and an overwhelmed sensation. You prefer to create a space with a peaceful and beautiful environment.  You might find yourself drawn to careers in entertainment, or customer service, or even healthcare. You dream of deep connections, late night talks, a starry sky and an idealistic perception of a romantic partner. You are always searching for oneness and you have a longing for a world tailored to your imagination. Establishing boundaries is crucial for you to develop your emotional and personal growth.Establishing boundaries is crucial for you to develop your emotional and personal growth.Establishing boundaries is crucial for you to develop your emotional and personal growth. Establishing boundaries is crucial for you to develop your emotional and personal growth. Ultimately you are all about understanding and fostering connections, creating harmony and establishing an understanding environment. You must accept your sensitive side, for it is not a weakness. Your empath, will help you heal, influence and bring people together.'
  },
  {
    LifeNumber: 3,
    title: 'The Inspirer',
    destiny: 'You are all about expansion and growth, you definitely have a winner mentality, but what sets you apart is your drive to be a winner all on your own. You would  consider yourself to be a one man army, you feel unstoppable when you are getting things done and do not have someone slowing you down. You want to be the one in control. You are someone who could be described using the words "knowledge" and "Advancement". You are a logical person and have a strategic outlook of things. You usually set high standards for yourself and hold people accountable for their doings. You definitely view success as a paramount objective. Even though you are all about the drive, you also possess a vibrant sense  of humor, you are very dynamic and you thrive in social settings. You love getting to know people, and spending time with friends and family. You have an extroverted persona, yet you also like to enjoy some alone time. People seem to enjoy your company and you are definitely a best friend to many. However you are quite picky when it comes to choosing your best friend or your close circle. You enjoy the company of people who want to be winners and may not be interested in gossip. You would definitely like a lead role in every field of life. Your strong strategic mindset helps you in various fields which require planning, organizing and a strategic execution, for example: Academics, business, politics or directorial positions.You exude confidence, but despite this you find yourself creating false facades, only letting people see the most polished, perfect side of you. You hate showing weakness or asking for help. You never want to ask for help, because most often you are the one helping people. This may also cause for you to not understand your own emotions or lead to you ignoring your emotions. It is crucial for you to recognize your shortcomings, or vulnerabilities, in order to strengthen connections and have genuine relations. With your energy and drive for success you can manifest anything you want, but you must also learn to enjoy life\'s pleasures.'
  },
  {
    LifeNumber: 4,
    title: 'The Foundation Builder',
    destiny: 'You are someone who likes thinking out of the box, you are unique. You very well maybe, a natural-born engineer, or an inventor of any kind. You do not like authorities, and you may often run into conflicts with authorities because of your rebellious spirit. You want to revolutionize new ideas, which may make people dislike you because what you do is out of the normal. Therefore you may be surrounded by fake people, enemies and people who might envy the person that you are. For the most part of your life, you may have been perceived as the black sheep of the class, of the family. You may also be inflicted with ADHD, you find peace in dancing to your own music. You exhibit good taste in music, fashion, and you like to challenge conventional norms. Your depth, and thoughtfulness defines your life. You want to make innovations and breakthroughs. You may have to face intense upheavals and storms all throughout your life. Things may not come as easily to you as it does to other people, but when things do happen for you, it is most often better that you could have imagined it to be. You possess a stark contrast within yourself - a contrast of both gentle and sensitive yet also a robust survival instinct. This duality within you helps you adapt and thrive in different circumstances. You are sensitive, yet remain practical. You yearn for stability, but underneath the desire for stability, you want to break down generational curses, society norms and rebuild a new world from scratch. You like to stay quiet about your successes and talents, this behavior can sometimes mask your potential and capabilities.  You like to get things done, you are searching for a connection and a sense of belonging with the world.'

  },
  {
    LifeNumber: 5,
    title: 'The Adventurer',
    destiny: 'You are an Orator, a natural born speaker. You have great social skills and you get along with everybody. People would often describe you as a social person or a social butterfly. You can be described by the following words: Vigor, communication, friendships and business. Making friends and establishing networks come easily to you. You have a lot of qualities, but the ones which really stand out are your abilities to understand situations swiftly and adapt to them, and your communication. You are quick to grasp different perspectives and set things into motion. You possess a vibrant energy. You thrive on excitement and change, you are in love with life and you are always looking for opportunities to engage with life through activities and making connections. You are very charismatic and possess a lot of charm, which is why a lot of people want to talk to you and become your friend. They are drawn to you. You are very good at speaking, you could sell a story and people would believe it, and you are magnetic in simple words. You are spontaneous, which enables you to connect with people quickly and open up to you. However, since you are so full of energy, sometimes you take on too many tasks at once and struggle to balance it all out.  Your quick thinking and the ability to adapt are your assets, however your social persona might be overbearing for some, which may lead people to believe that you are egocentric or manipulative. The way you carry yourself and move on in life may lead some people to think that you are superficial, and you do not care about other people genuinely. You need to choose your ideas carefully, as you cannot seem to stay on one track for too long. You may get burnt out too quickly or get overwhelmed due to multiple things going on in your mind. You may start to feel stuck and closed off. On the other hand, you may become more impulsive and may experience burning out.'

  },
  {
    LifeNumber: 6,
    title: 'The Protector',
    destiny: 'You possess a magnetic charm and an effortless ability to attract others. You are very sensual in nature, and you are very good at flirting, you exude a natural allure. You value life at home, harmony and comfort. You enjoy caring for others, upholding traditions, tranquility. You find that your presence uplifts the mood in a room and people vibe with you, you bring people together. You are all about assisting others, loyalty and love, however you may be stubborn at times and may manipulate others emotionally, causing conflicts of sorts. You love going above and beyond for your loved ones, however sometimes you may end up feeling burdened by it or unappreciated. Your care-giving nature usually attracts people who are in need of your assistance. You find people around you looking up to you for solutions to their problems or seeking emotional assistance from you. You must focus on mananging your own emotions and establishing boundaries, you need to focus on your own happiness as well and not be completely focused on helping others all the time. You are a provider, and you hate being provided for, however being taken care of wont make you any less of a provider. You must learn to navigate relationships and take care of yourself.'

  },
  {
    LifeNumber: 7,
    title: 'The Seeker of Truth',
    destiny: 'Your number is a shadow number. You are seeking something, a deeper meaning, some profound knowledge. You are an adventurer. You are on your path of discovering spirituality, depths of human minds. You crave insight and understanding involved behind every happening and action. You have a "sixth sense" you are capable of understanding people\'s intentions very well and you have a very well-developed gut instinct. You may have a premonition before something is about to happen. You are deeply intertwined with the energies of introspection, spirituality and intellectual exploration. You have always been attracted to intuition, mysteries, psychic abilities and unveiling the mysteries of the universe. You have a very active imagination; you find joy in expressing yourself through art, music, writing or anyway that would allow you to pen down your inner wisdom into words. You may seem distant, rude or unapproachable to many, but you have a deep sense of wisdom within you. Like the calm waters, your wisdom is deep and calm. You are very sensitive, and you find trouble expressing yourself in social settings. You search for a understanding relationship whether it be friendships or something more. You search for a dep understanding, sometimes you find yourself wondering if you even belong to this world sometimes you long for a distant place, you dont even know if it exists. Sometimes you find it comfortable to sit with your thoughts and pull yourself away from social gatherings. This trait may make relationships challenging for you, as you often need space and solitude to recharge and reflect. You need to learn to balance your need for isolation and your desire for human connection. If left unbalanced, you may become too withdrawn, shutting out spiritual connections as well. You need to trust your insights a lot more. Your purpose here is to share your wisdom and deep understanding of life to help people and heal.'

  },
  {
    LifeNumber: 8,
    title: 'The Visionary Leader',
    destiny: 'You are born to make a major change in the world and to cretate something that will last forever. You want to build things slowly and thoroughly, you are quite practical in your outlook towards life, and you make sure everything is going according to your plan. One step at a time. You have seen the hard side of life, which has also taught you to deal with difficult and uncomfortable situations, that others may shy away from. You are a beacon for strength, ambition and you are exceptional when it comes to navigating through the complexities of life. You are the source of strength, emotional support and reassurance for people close to you and loved ones. You possess a robust personality and a very sharp survival instinct. You may seem to have a hard exterior, however you are a genuinely good person and have a lot of wisdom. You often find yourself creating your own ways or paths in life, you are not easily swayed by others opinions, and you have strong faith in yourself and your own individuality.You often find yourself to be driven by a blend of wanting materialistic things and spiritual depth, when you balance these two qualities, you will be able to experience a fulfilling existence that will satisfy both aspects of your life. You may be struggling with feeling of loneliness and being misunderstood; you often view seeking help as a weakness. You have an image of a self-sufficient and strong personality, and you try to maintain that image any way possible. People may think of you as a reserved or cynical person, however in the interior you are very loyal to those you love, and respect and you have a very strong moral compass as well. You may have a natural inclination towards philosophy, art and in general any field that allows you to lead. You have great leadership qualities. Your journey is all about mastering the art of balance between the material world and your spiritual self, trusting and forgiving and putting faith in the trials and tribulations of life. You need to harness your inherent power and use it to create an impact on this world.'

  },
  {
    LifeNumber: 9,
    title: 'The Compassionate Sage',
    destiny: 'You are everything, your number is 9, it is the highest number there is. You are nothing and everything all at once. You are an embodiment of strength, humanitarianism and a deep understanding of human experience. You are a combination of the intensity a warrior possesses with the sensitivity of a healer. You possess tremendous physical strength and mental strength, and a deep sensitivity which may not be apparent at first glance. Your strength comes from within, and you do not get defeated easily, you challenge life and take the bull by its horns. You are scared, but you never let it overpower your drive to win. And you win, you achieve things in life, even if people around you are not able to see your potential. You would fight battles for justice and peace, both with intensity and empathy. You had a tough childhood, where you felt like the black sheep of the family. You are a natural leader; you have an intense desire to improve the world.  To make it a better place. You often feel as if your purpose here is bigger than yourself and the cause of the battles you fight are for greater good. Which is why you have been attracted to studies of law, politics or social work. You want to understand and motivate others and push them towards honesty and integrity. You value honesty highly, which is your most notable trait. Howvever, at times your honesty can lead to misunderstandings or hurt feelings, if not used with tact and consideration. Your number is that accumulation of all other numbers, this means you would have to experience hardships faced by all other numbers. These experiences are meant to help you build your spiritual and emotional knowledge. You have discovered that every challenge you have faced has taught you to be more understanding and empathetic. It has helped you build your character. If your limits are pushed, you may have intense emotional expressions. This explosive energy, if harnessed and used constructively enables you to stand up for yourself and protect others. You need to balance this energy. Your journey here is all about fighting battles for higher ideals and healing that is broken, whether that be a system or people. Your profound strength and sensitivity make you a dangerous yet very compassionate warrior. Once you accept your warrior and healing nature, you will be able to make deep impacts on the lives of those around you.'

  }
]
